#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^\[(INIT|FEAT|TEST|FIX|DOCS|STYLE|REFACTOR|DESIGN|!HOTFIX|!BREAKING CHANGE|CHORE|COMMENT|RENAME|REMOVE|ADD|REVERT)\] : .+$"

# Use grep with Perl-compatible regex for emoji support
if ! echo "$message" | grep -Pq "$requiredPattern"; then
  echo "=========================================================================="
  echo "======================   🚨 WRONG COMMIT MESSAGE!   ======================"
  echo "=========================================================================="
  echo "============== Format should be => [type]: [subject] ====================="
  echo "== Allowed Types: INIT|FEAT|TEST|FIX|DOCS|STYLE|REFACTOR|DESIGN|!HOTFIX|!BREAKING CHANGE|CHORE|COMMENT|RENAME|REMOVE|ADD|REVERT =="
  echo "== EXAMPLE =>[FEAT]: Add new feature                ======================"
  echo "=========================================================================="
  echo "== Your commit message was => $message "
  echo "== For more information, check script in .husky/commit-msg or README.md =="
  echo "=========================================================================="
  exit 1
else
  echo "=========================================================================="
  echo "=======================      COMMIT CREATED!!      ======================="
  echo "=========================================================================="
fi